'use client';
import {useState} from 'react';
type Choice={id:string;name:string;class_id?:string;subject_id?:string};
export function ContentOrganization({classes,subjects,chapters,initial,children}:{classes:Choice[];subjects:Choice[];chapters:Choice[];initial?:{class_id:string;subject_id:string;chapter_id:string|null;topic?:string|null};children?:React.ReactNode}){
 const [classId,setClassId]=useState(initial?.class_id||'');const [subjectId,setSubjectId]=useState(initial?.subject_id||'');const [chapterId,setChapterId]=useState(initial?.chapter_id||'');
 const selectedClass=classes.find(c=>c.id===classId)?.name||'';const isClass5=selectedClass==='Class 5';const later=/^Class (?:[6-9]|10)$/.test(selectedClass);
 const topic=initial?.topic||'';const pages=/(?:^| · )Pages? (\d+)(?:-(\d+))?/.exec(topic);const kd=/(?:^| · )K\.D (\d+(?:\.\d+)?(?:-\d+(?:\.\d+)?)?)/.exec(topic);
 return <><label>Class<select className="field" name="class_id" required value={classId} onChange={e=>{setClassId(e.target.value);setSubjectId('');setChapterId('')}}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject<select className="field" name="subject_id" required value={subjectId} onChange={e=>{setSubjectId(e.target.value);setChapterId('')}}><option value="">Select subject</option>{subjects.filter(x=>x.class_id===classId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{!isClass5&&<label>Chapter (optional)<select className="field" name="chapter_id" value={chapterId} onChange={e=>setChapterId(e.target.value)}><option value="">No chapter</option>{chapters.filter(x=>x.subject_id===subjectId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><a href="/admin/chapters" style={{fontWeight:700,color:'#164d3c'}}>+ Add a new chapter ↗</a></label>}{isClass5&&<input type="hidden" name="chapter_id" value=""/>}{children}
 <label>Page number {isClass5?'(required)':'(optional)'}<input className="field" type="number" min="1" name="page_start" required={isClass5} placeholder="1" defaultValue={pages?.[1]||''}/></label><label>Last page (optional for a range)<input className="field" type="number" min="1" name="page_end" placeholder="20" defaultValue={pages?.[2]||''}/></label>{later&&<label>K.D label (optional, can be used with pages)<input className="field" name="kd_label" placeholder="1.1 or 1.1-1.6" defaultValue={kd?.[1]||''}/></label>}
 <label className="wide">Other topic (optional)<input className="field" name="topic" placeholder="Shown when no page or K.D label is set" defaultValue={pages||kd?'':topic}/></label></>;
}
