'use server';
import {revalidatePath} from 'next/cache';import {redirect} from 'next/navigation';import {admin,configured,db} from './supabase';import {z} from 'zod';
const slug=(s:string)=>s.toLowerCase().trim().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
async function guard(){if(!configured()||!await admin())throw new Error('Admin access required');return db()}
const text=(f:FormData,k:string)=>String(f.get(k)||'').trim();
export async function signIn(form:FormData){if(!configured())redirect('/admin/login?error=setup');const s=await db();const {error}=await s.auth.signInWithPassword({email:text(form,'email'),password:text(form,'password')});if(error)redirect('/admin/login?error=invalid');redirect('/admin')}
export async function signOut(){if(configured())await(await db()).auth.signOut();redirect('/admin/login')}
export async function saveEntity(table:'classes'|'subjects'|'chapters',form:FormData){const s=await guard();const id=text(form,'id'),name=text(form,table==='chapters'?'title':'name');if(!name||name.length>180)throw Error('Enter a title under 180 characters');let payload:Record<string,unknown>={description:text(form,'description').slice(0,2000),sort_order:Number(form.get('sort_order')||0)};if(table==='chapters'){const subject_id=text(form,'subject_id');if(!subject_id)throw Error('Subject required');payload={...payload,title:name,slug:slug(name),subject_id}}else if(table==='subjects'){const class_id=text(form,'class_id');if(!class_id)throw Error('Class required');payload={...payload,name,slug:slug(name),class_id}}else payload={...payload,name,slug:slug(name)};
const {error}=id?await s.from(table).update(payload).eq('id',id):await s.from(table).insert(payload);if(error)throw Error('Could not save item. Check for a duplicate name.');revalidatePath('/');revalidatePath('/classes');revalidatePath('/admin');redirect(`/admin/${table}?saved=1`)}
export async function deleteEntity(table:'classes'|'subjects'|'chapters'|'content',id:string){const s=await guard();const {error}=await s.from(table).delete().eq('id',id);if(error)throw Error('Could not delete this item');revalidatePath('/');revalidatePath('/admin');revalidatePath('/classes')}
const contentSchema=z.object({title:z.string().min(2).max(180),type:z.enum(['note','video','image','resource']),class_id:z.string().uuid(),subject_id:z.string().uuid(),chapter_id:z.string().uuid(),status:z.enum(['draft','published'])});
export async function saveContent(form:FormData){const s=await guard();const id=text(form,'id');const payload=contentSchema.parse(Object.fromEntries(['title','type','class_id','subject_id','chapter_id','status'].map(k=>[k,text(form,k)])));const {data:subject}=await s.from('subjects').select('id,class_id').eq('id',payload.subject_id).single();const {data:chapter}=await s.from('chapters').select('id,subject_id').eq('id',payload.chapter_id).single();if(subject?.class_id!==payload.class_id||chapter?.subject_id!==payload.subject_id)throw Error('Choose a subject and chapter belonging to this class');const upload=form.get('file');let file_url:string|undefined; if(upload instanceof File&&upload.size){const allowed=['application/pdf','image/jpeg','image/png','image/webp','video/mp4','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];if(!allowed.includes(upload.type)||upload.size>50*1024*1024)throw Error('Unsupported file or file exceeds 50 MB');file_url=`content/${crypto.randomUUID()}/${upload.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error:uploadError}=await s.storage.from('materials').upload(file_url,upload,{contentType:upload.type,upsert:false});if(uploadError)throw Error('Upload failed. Please retry.')}const row={...payload,file_url,slug:slug(payload.title)+(id?'':'-'+Math.random().toString(36).slice(2,7)),description:text(form,'description').slice(0,12000),topic:text(form,'topic').slice(0,120),video_url:text(form,'video_url').slice(0,1000),tags:text(form,'tags').split(',').map(x=>x.trim()).filter(Boolean).slice(0,15),featured:form.get('featured')==='on',premium:form.get('premium')==='on',allow_download:form.get('allow_download')==='on'};const {error}=id?await s.from('content').update({...row,slug:undefined,file_url:file_url||undefined}).eq('id',id):await s.from('content').insert(row);if(error){if(file_url)await s.storage.from('materials').remove([file_url]);throw Error('Could not save content')}revalidatePath('/');revalidatePath('/admin/content');redirect('/admin/content?saved=1')}
export async function togglePublish(id:string,status:'draft'|'published'){const s=await guard();await s.from('content').update({status}).eq('id',id);revalidatePath('/');revalidatePath('/admin/content')}
