import {configured,db} from './supabase';import {cache} from 'react';
export type Class={id:string;name:string;slug:string;description:string|null;thumbnail_url:string|null;sort_order:number};
export type Subject={id:string;class_id:string;name:string;slug:string;description:string|null;icon:string|null;sort_order:number};
export type Chapter={id:string;subject_id:string;title:string;slug:string;description:string|null;thumbnail_url:string|null;sort_order:number};
export type Content={id:string;title:string;slug:string;description:string|null;type:'note'|'video'|'image'|'resource';class_id:string;subject_id:string;chapter_id:string|null;topic:string|null;thumbnail_url:string|null;file_url:string|null;file_urls?:string[]|null;video_url:string|null;status:'draft'|'published';featured:boolean;premium:boolean;allow_download:boolean;views:number;created_at:string;updated_at:string;duration_seconds:number|null;tags:string[]|null};
const sampleClasses:Class[]=[5,6,7,8,9,10,11,12].map((n,i)=>({id:String(n),name:`Class ${n}`,slug:String(n),description:`Clear lessons and carefully organized resources for Class ${n}.`,thumbnail_url:null,sort_order:i}));
const sampleSubjects:Subject[]=['Mathematics','Science','English','History','Geography','Bengali'].map((name,i)=>({id:`s${i}`,class_id:'7',name,slug:name.toLowerCase(),description:null,icon:null,sort_order:i}));
const sampleChapters:Chapter[]=[{id:'ch1',subject_id:'s0',title:'Integers and number lines',slug:'integers-and-number-lines',description:'Build confidence with negative numbers, ordering and operations.',thumbnail_url:null,sort_order:1},{id:'ch2',subject_id:'s0',title:'Fractions and decimals',slug:'fractions-and-decimals',description:'Make sense of fractions, decimals and practical problems.',thumbnail_url:null,sort_order:2}];
const sampleContent:Content[]=[{id:'demo-1',title:'Understanding integers',slug:'understanding-integers',description:'A clear introduction to positive and negative numbers, with examples you can try yourself.',type:'note',class_id:'7',subject_id:'s0',chapter_id:'ch1',topic:'Number systems',thumbnail_url:null,file_url:null,video_url:null,status:'published',featured:true,premium:false,allow_download:false,views:0,created_at:'2026-09-01T00:00:00Z',updated_at:'2026-09-01T00:00:00Z',duration_seconds:null,tags:['Mathematics','Class 7']}];
export const classes=cache(async function classes(){if(!configured())return sampleClasses;const {data}=await (await db()).from('classes').select('*').order('sort_order');return data as Class[]||[]});
export const subjects=cache(async function subjects(classId?:string){if(!configured())return sampleSubjects.filter(s=>!classId||s.class_id===classId);let q=(await db()).from('subjects').select('*').order('sort_order');if(classId)q=q.eq('class_id',classId);const {data}=await q;return data as Subject[]||[]});
export const chapters=cache(async function chapters(subjectId?:string){if(!configured())return sampleChapters.filter(c=>!subjectId||c.subject_id===subjectId);let q=(await db()).from('chapters').select('*').order('sort_order');if(subjectId)q=q.eq('subject_id',subjectId);const {data}=await q;return data as Chapter[]||[]});
export async function content(filters?:{type?:string;chapter?:string;classId?:string;subjectId?:string;premium?:boolean;query?:string;limit?:number}){if(!configured())return sampleContent.filter(c=>(!filters?.type||c.type===filters.type)&&(!filters?.chapter||c.chapter_id===filters.chapter)&&(!filters?.classId||c.class_id===filters.classId)&&(!filters?.subjectId||c.subject_id===filters.subjectId)&&(!filters?.premium||c.premium)&&(!filters?.query||c.title.toLowerCase().includes(filters.query.toLowerCase())));let q=(await db()).from('content').select('*').eq('status','published').order('created_at',{ascending:false}).limit(filters?.limit||60);if(filters?.type)q=q.eq('type',filters.type);if(filters?.chapter)q=q.eq('chapter_id',filters.chapter);if(filters?.classId)q=q.eq('class_id',filters.classId);if(filters?.subjectId)q=q.eq('subject_id',filters.subjectId);if(filters?.premium)q=q.eq('premium',true);if(filters?.query)q=q.ilike('title',`%${filters.query.replace(/[%_,]/g,'')}%`);const {data}=await q;return data as Content[]||[]}
