import {configured,db} from './supabase';import {cache} from 'react';
export type Class={id:string;name:string;slug:string;description:string|null;thumbnail_url:string|null;sort_order:number};
export type Subject={id:string;class_id:string;name:string;slug:string;description:string|null;icon:string|null;sort_order:number};
export type Chapter={id:string;subject_id:string;title:string;slug:string;description:string|null;thumbnail_url:string|null;sort_order:number};
export type Content={id:string;title:string;slug:string;description:string|null;type:'note'|'video'|'image'|'resource';class_id:string;subject_id:string;chapter_id:string|null;topic:string|null;thumbnail_url:string|null;file_url:string|null;file_urls?:string[]|null;video_url:string|null;status:'draft'|'published';featured:boolean;premium:boolean;allow_download:boolean;views:number;created_at:string;updated_at:string;duration_seconds:number|null;tags:string[]|null};
const sampleClasses:Class[]=[];
const sampleSubjects:Subject[]=[];
const sampleChapters:Chapter[]=[];
const sampleContent:Content[]=[];
export const classes=cache(async function classes(){if(!configured())return sampleClasses;const {data}=await (await db()).from('classes').select('*').order('sort_order');return data as Class[]||[]});
export const subjects=cache(async function subjects(classId?:string){if(!configured())return sampleSubjects.filter(s=>!classId||s.class_id===classId);let q=(await db()).from('subjects').select('*').order('sort_order');if(classId)q=q.eq('class_id',classId);const {data}=await q;return data as Subject[]||[]});
export const chapters=cache(async function chapters(subjectId?:string){if(!configured())return sampleChapters.filter(c=>!subjectId||c.subject_id===subjectId);let q=(await db()).from('chapters').select('*').order('sort_order');if(subjectId)q=q.eq('subject_id',subjectId);const {data}=await q;return data as Chapter[]||[]});
export async function content(filters?:{type?:string;chapter?:string;classId?:string;subjectId?:string;premium?:boolean;query?:string;limit?:number}){if(!configured())return sampleContent.filter(c=>(!filters?.type||c.type===filters.type)&&(!filters?.chapter||c.chapter_id===filters.chapter)&&(!filters?.classId||c.class_id===filters.classId)&&(!filters?.subjectId||c.subject_id===filters.subjectId)&&(!filters?.premium||c.premium)&&(!filters?.query||c.title.toLowerCase().includes(filters.query.toLowerCase())));let q=(await db()).from('content').select('*').eq('status','published').order('created_at',{ascending:false}).limit(filters?.limit||60);if(filters?.type)q=q.eq('type',filters.type);if(filters?.chapter)q=q.eq('chapter_id',filters.chapter);if(filters?.classId)q=q.eq('class_id',filters.classId);if(filters?.subjectId)q=q.eq('subject_id',filters.subjectId);if(filters?.premium)q=q.eq('premium',true);if(filters?.query)q=q.ilike('title',`%${filters.query.replace(/[%_,]/g,'')}%`);const {data}=await q;return data as Content[]||[]}
